#ifndef ROPESIM_H
#define ROPESIM_H

/* AUTO-GENERATED by cbindgen — do not edit */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define RETIREMENT_THRESHOLD 0.85

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// UIAA fall factor: fall_dist / rope_out, clamped to [0, 2].
// Returns -1.0 if rope_out <= 0.
double ropesim_compute_fall_factor(double fall_dist, double rope_out);

// UIAA 101 / EN 892 peak impact force (kN) with wet and temperature
// modifiers applied.  `is_wet`: 0 = dry, nonzero = wet.
double ropesim_compute_impact_force(double mass_kg,
                                    double fall_factor,
                                    double stiffness_kn,
                                    double belay_friction,
                                    int32_t is_wet,
                                    double temp_celsius);

// RK4 force–time curve.  Writes up to `buffer_len` force samples (kN) into
// caller-allocated `out_buffer`; returns the number of values written.
// Returns 0 on null/empty buffer.
int32_t ropesim_compute_force_curve(double mass_kg,
                                    double fall_dist,
                                    double rope_out,
                                    double stiffness_kn,
                                    double damping,
                                    double dt_ms,
                                    double *out_buffer,
                                    int32_t buffer_len);

// Sliding-X force distribution.  Writes per-bolt force (kN) to out params.
void ropesim_sliding_x_distribution(double load_kn,
                                    double angle_deg,
                                    double *out_bolt_a,
                                    double *out_bolt_b);

// Quad anchor force distribution.  `extension_limiter`: 0 = no, nonzero = yes.
void ropesim_quad_distribution(double load_kn,
                               double angle_deg,
                               int32_t extension_limiter,
                               double *out_bolt_a,
                               double *out_bolt_b);

// Create a physics world.  Returns an opaque pointer; destroy with
// ropesim_world_destroy.
void *ropesim_world_create(double gravity);

// Destroy a world created by ropesim_world_create.  Passing null is a no-op.
void ropesim_world_destroy(void *world);

// Add a rope between start[3] and end[3].  Returns the handle of the rope's
// *last* link (climber attachment point), or -1 on error.
int32_t ropesim_world_add_rope(void *world,
                               const double *start,
                               const double *end,
                               double length_m,
                               double mass_per_m,
                               double link_len,
                               double stiffness,
                               double damping);

// Add a bolt.  `bolt_type`: 0 = expansion, 1 = glue-in (cosmetic only).
// Returns gear handle or -1.
int32_t ropesim_world_add_bolt(void *world, const double *pos, double mbs_kn, int32_t bolt_type);

// Add a cam.  `quality` 0–1, `pull_dir[3]` expected pull-out direction.
// Returns gear handle or -1.
int32_t ropesim_world_add_cam(void *world,
                              const double *pos,
                              double mbs_kn,
                              double quality,
                              const double *pull_dir);

// Attach a climber to a rope handle (as returned by add_rope).
// Returns climber handle or -1.
int32_t ropesim_world_add_climber(void *world, int32_t rope_handle, double mass_kg);

// Add a ledge/rock face from a triangle-fan vertex list (xyz triples).
// Returns 0 on success, -1 on error.
int32_t ropesim_world_add_ledge(void *world,
                                const double *verts,
                                int32_t vert_count,
                                double friction);

// Add a belayer.  `device_type` uses the RopesimBelayDevice enum values;
// `dynamic`: 0 = anchored/static, nonzero = dynamic (can be lifted).
// Returns belayer handle or -1.
int32_t ropesim_world_add_belayer(void *world,
                                  const double *pos,
                                  double mass_kg,
                                  int32_t device_type,
                                  int32_t dynamic);

// Clip rope link `rope_link` (index along the rope) to a gear handle.
void ropesim_world_clip_rope(void *world, int32_t rope_link, int32_t gear_handle);

// Advance the simulation by `dt` seconds.
void ropesim_world_step(void *world, double dt);

// Write rope link positions as xyz triples into `out_buf`
// (capacity `buf_len` doubles).  Returns the number of f64 values written.
int32_t ropesim_world_get_rope_positions(void *world, double *out_buf, int32_t buf_len);

// Current estimated force (kN) at a gear handle.
double ropesim_world_get_force_at_gear(void *world, int32_t gear_handle);

// Current estimated anchor force (kN).
double ropesim_world_get_anchor_force(void *world);

// Climber position (xyz) written to out[3].
void ropesim_world_get_climber_position(void *world, double *out);

// Static elongation (m) under a sustained load.
double ropesim_static_elongation(double static_pct, double load_kg, double length_m);

// Rappel anchor load (kN) during steady descent (no sudden stop).
double ropesim_rappel_load(double mass_kg, double device_friction, double speed_mps);

// Haul system forces.  `system_type`: 0 = 3:1, 1 = 5:1, 2 = 6:1, 3 = piggyback.
// Writes actual mechanical advantage and hauler effort (N).
void ropesim_haul_forces(int32_t system_type,
                         double load_kg,
                         double friction,
                         double *out_actual_ma,
                         double *out_hauler_effort);

// Rope degradation with accumulated falls.  Mirrors ropesim.rope.Rope.degrade:
// stiffness (and impact force) rise up to +20 % at end of rated life.
// `out_retirement_warning`: 0 = fine, 1 = inspect (≥80 %), 2 = retire (≥100 %).
void ropesim_degrade_rope(double base_stiffness,
                          int32_t falls_taken,
                          int32_t rated_falls,
                          double *out_stiffness,
                          double *out_impact_force,
                          int32_t *out_retirement_warning);

// Twin-rope pair forces (kN) through a shared piece.
void ropesim_twin_rope_forces(double rope_a_stiffness,
                              double rope_b_stiffness,
                              double mass_kg,
                              double fall_factor,
                              double inter_rope_friction,
                              double *out_force_a,
                              double *out_force_b);

// Half-rope pair forces (kN); `active_rope` 0 or 1 selects the strand
// arresting this fall.
void ropesim_half_rope_forces(double rope_a_stiffness,
                              double rope_b_stiffness,
                              double mass_kg,
                              double fall_factor,
                              int32_t active_rope,
                              double *out_force_a,
                              double *out_force_b);

// Knot strength retention factor (0–1).  `knot_type` uses the RopesimKnotType
// enum values; unknown values return the conservative clove-hitch factor.
double ropesim_knot_strength_factor(int32_t knot_type, double rope_diameter_mm);

// Knotted multi-strand cord anchor strength (kN).
double ropesim_cord_anchor_strength(double cord_mbs_kn,
                                    int32_t knot_type,
                                    int32_t num_strands,
                                    double diameter_mm);

// Sheath abrasion increment for one rope-over-rock contact.
// `rock_type` uses the RopesimRockType enum values.
double ropesim_abrasion_increment(int32_t rock_type,
                                  double contact_force_kn,
                                  double contact_duration_s,
                                  double rope_velocity_mps);

// Fold an abrasion increment into a running score.  Returns the new score
// (0–1) and writes the visual rating (RopesimSheathRating values) and
// retirement flag (0/1).
double ropesim_accumulate_sheath_wear(double current_score,
                                      double increment,
                                      double sheath_pct,
                                      int32_t *out_rating,
                                      int32_t *out_needs_retirement);

// Fall probability per attempt and cumulative risk over `attempts`.
// `pitch_grade` / climber grade use YDS numeric (5.10a → 10.1).
// Climber grade is fixed at the route grade minus `grade_margin`.
//
// Simpler two-output form required by the GUI results panel:
// writes probability per attempt and expected falls over `attempts`.
void ropesim_fall_probability(double pitch_grade,
                              double climber_grade,
                              int32_t style,
                              int32_t attempts,
                              double *out_prob_per_attempt,
                              double *out_expected_falls);

// Cumulative risk projection.  Outputs: expected falls, expected total
// force (kN), rope life consumed (%), retirement climbs remaining.
void ropesim_cumulative_risk(double fall_probability,
                             int32_t num_attempts,
                             double peak_force_kn,
                             int32_t rope_rated_falls,
                             int32_t falls_taken_so_far,
                             double *out_expected_falls,
                             double *out_expected_total_force_kn,
                             double *out_rope_life_consumed_pct,
                             int32_t *out_retirement_climbs_remaining);

// Dynamic belay force-reduction factor (0.55–1.0) to multiply into peak
// impact force.  `device_type` uses the RopesimBelayDevice enum values.
double ropesim_dynamic_belay_reduction(double climber_mass_kg,
                                       double belayer_mass_kg,
                                       int32_t device_type,
                                       int32_t belayer_standing,
                                       int32_t soft_catch_technique);

// ABI version of this header.  The C++ bridge asserts on this at startup.
int32_t ropesim_abi_version(void);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* ROPESIM_H */
