/* AUTO-GENERATED by cbindgen — do not edit */
/* Regenerated on every `cargo build` of ropesim/_rustcore (see build.rs).   */
/* This checked-in copy matches _rustcore/src/ffi.rs, ABI version 3.        */

#ifndef ROPESIM_H
#define ROPESIM_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Knot types (stable discriminants) */
typedef enum RopesimKnotType {
    ROPESIM_KNOT_TYPE_FIGURE_EIGHT_RETRACE = 0,
    ROPESIM_KNOT_TYPE_FIGURE_EIGHT_ON_BIGHT = 1,
    ROPESIM_KNOT_TYPE_BOWLINE = 2,
    ROPESIM_KNOT_TYPE_CLOVE_HITCH = 3,
    ROPESIM_KNOT_TYPE_MUNTER_HITCH = 4,
    ROPESIM_KNOT_TYPE_DOUBLE_FISHERMANS = 5,
    ROPESIM_KNOT_TYPE_OVERHAND_ON_BIGHT = 6,
    ROPESIM_KNOT_TYPE_ALPINE_BUTTERFLY = 7,
} RopesimKnotType;

/* Rock types (stable discriminants) */
typedef enum RopesimRockType {
    ROPESIM_ROCK_TYPE_GRANITE = 0,
    ROPESIM_ROCK_TYPE_LIMESTONE = 1,
    ROPESIM_ROCK_TYPE_SANDSTONE = 2,
    ROPESIM_ROCK_TYPE_BASALT = 3,
    ROPESIM_ROCK_TYPE_ICE = 4,
} RopesimRockType;

/* Sheath visual rating (stable discriminants) */
typedef enum RopesimSheathRating {
    ROPESIM_SHEATH_RATING_NEW = 0,
    ROPESIM_SHEATH_RATING_GOOD = 1,
    ROPESIM_SHEATH_RATING_WORN = 2,
    ROPESIM_SHEATH_RATING_CRITICAL = 3,
} RopesimSheathRating;

/* Climbing style (stable discriminants) */
typedef enum RopesimClimbingStyle {
    ROPESIM_CLIMBING_STYLE_SPORT = 0,
    ROPESIM_CLIMBING_STYLE_TRAD = 1,
    ROPESIM_CLIMBING_STYLE_BOULDER = 2,
} RopesimClimbingStyle;

/* Belay devices (stable discriminants) */
typedef enum RopesimBelayDevice {
    ROPESIM_BELAY_DEVICE_ATC = 0,
    ROPESIM_BELAY_DEVICE_GRI_GRI = 1,
    ROPESIM_BELAY_DEVICE_TUBE = 2,
    ROPESIM_BELAY_DEVICE_REVERSO = 3,
    ROPESIM_BELAY_DEVICE_REVERSO_GUIDE = 4,
    ROPESIM_BELAY_DEVICE_MEGA_JUL = 5,
    ROPESIM_BELAY_DEVICE_GIGA_JUL = 6,
    ROPESIM_BELAY_DEVICE_CLICK_UP = 7,
    ROPESIM_BELAY_DEVICE_I_DEVICE = 8,
    ROPESIM_BELAY_DEVICE_SUM = 9,
    ROPESIM_BELAY_DEVICE_MUNTER = 10,
} RopesimBelayDevice;

/* ── Fall physics ─────────────────────────────────────────────────────── */

/* UIAA fall factor: fall_dist / rope_out, clamped to [0, 2].
   Returns -1.0 if rope_out <= 0. */
double ropesim_compute_fall_factor(double fall_dist, double rope_out);

/* UIAA 101 / EN 892 peak impact force (kN) with wet and temperature
   modifiers applied.  is_wet: 0 = dry, nonzero = wet. */
double ropesim_compute_impact_force(double mass_kg,
                                    double fall_factor,
                                    double stiffness_kn,
                                    double belay_friction,
                                    int32_t is_wet,
                                    double temp_celsius);

/* RK4 force-time curve.  Writes up to buffer_len samples (kN) into the
   caller-allocated out_buffer; returns the number of values written. */
int32_t ropesim_compute_force_curve(double mass_kg,
                                    double fall_dist,
                                    double rope_out,
                                    double stiffness_kn,
                                    double damping,
                                    double dt_ms,
                                    double *out_buffer,
                                    int32_t buffer_len);

/* ── Anchors ──────────────────────────────────────────────────────────── */

void ropesim_sliding_x_distribution(double load_kn,
                                    double angle_deg,
                                    double *out_bolt_a,
                                    double *out_bolt_b);

void ropesim_quad_distribution(double load_kn,
                               double angle_deg,
                               int32_t extension_limiter,
                               double *out_bolt_a,
                               double *out_bolt_b);

/* ── Rapier world (opaque pointer) ────────────────────────────────────── */

void *ropesim_world_create(double gravity);
void ropesim_world_destroy(void *world);

/* Returns the handle of the rope's last link (climber attachment), or -1. */
int32_t ropesim_world_add_rope(void *world,
                               const double *start,
                               const double *end,
                               double length_m,
                               double mass_per_m,
                               double link_len,
                               double stiffness,
                               double damping);

int32_t ropesim_world_add_bolt(void *world, const double *pos, double mbs_kn,
                               int32_t bolt_type);

int32_t ropesim_world_add_cam(void *world, const double *pos, double mbs_kn,
                              double quality, const double *pull_dir);

int32_t ropesim_world_add_climber(void *world, int32_t rope_handle, double mass_kg);

int32_t ropesim_world_add_ledge(void *world, const double *verts,
                                int32_t vert_count, double friction);

int32_t ropesim_world_add_belayer(void *world, const double *pos, double mass_kg,
                                  int32_t device_type, int32_t dynamic);

void ropesim_world_clip_rope(void *world, int32_t rope_link, int32_t gear_handle);

void ropesim_world_step(void *world, double dt);

/* Writes xyz triples; returns number of doubles written. */
int32_t ropesim_world_get_rope_positions(void *world, double *out_buf, int32_t buf_len);

double ropesim_world_get_force_at_gear(void *world, int32_t gear_handle);
double ropesim_world_get_anchor_force(void *world);
void ropesim_world_get_climber_position(void *world, double *out);

/* ── Static elongation / rappel / haul ────────────────────────────────── */

double ropesim_static_elongation(double static_pct, double load_kg, double length_m);
double ropesim_rappel_load(double mass_kg, double device_friction, double speed_mps);

/* system_type: 0 = 3:1, 1 = 5:1, 2 = 6:1, 3 = piggyback */
void ropesim_haul_forces(int32_t system_type, double load_kg, double friction,
                         double *out_actual_ma, double *out_hauler_effort);

/* ── Rope degradation ─────────────────────────────────────────────────── */

/* out_retirement_warning: 0 = fine, 1 = inspect (>=80%), 2 = retire. */
void ropesim_degrade_rope(double base_stiffness, int32_t falls_taken,
                          int32_t rated_falls, double *out_stiffness,
                          double *out_impact_force, int32_t *out_retirement_warning);

/* ── v3 new physics ───────────────────────────────────────────────────── */

void ropesim_twin_rope_forces(double rope_a_stiffness, double rope_b_stiffness,
                              double mass_kg, double fall_factor,
                              double inter_rope_friction,
                              double *out_force_a, double *out_force_b);

void ropesim_half_rope_forces(double rope_a_stiffness, double rope_b_stiffness,
                              double mass_kg, double fall_factor,
                              int32_t active_rope,
                              double *out_force_a, double *out_force_b);

double ropesim_knot_strength_factor(int32_t knot_type, double rope_diameter_mm);

double ropesim_cord_anchor_strength(double cord_mbs_kn, int32_t knot_type,
                                    int32_t num_strands, double diameter_mm);

double ropesim_abrasion_increment(int32_t rock_type, double contact_force_kn,
                                  double contact_duration_s, double rope_velocity_mps);

/* Returns the new score (0-1). */
double ropesim_accumulate_sheath_wear(double current_score, double increment,
                                      double sheath_pct, int32_t *out_rating,
                                      int32_t *out_needs_retirement);

void ropesim_fall_probability(double pitch_grade, double climber_grade,
                              int32_t style, int32_t attempts,
                              double *out_prob_per_attempt, double *out_expected_falls);

void ropesim_cumulative_risk(double fall_probability, int32_t num_attempts,
                             double peak_force_kn, int32_t rope_rated_falls,
                             int32_t falls_taken_so_far,
                             double *out_expected_falls,
                             double *out_expected_total_force_kn,
                             double *out_rope_life_consumed_pct,
                             int32_t *out_retirement_climbs_remaining);

double ropesim_dynamic_belay_reduction(double climber_mass_kg, double belayer_mass_kg,
                                       int32_t device_type, int32_t belayer_standing,
                                       int32_t soft_catch_technique);

/* ── Version ──────────────────────────────────────────────────────────── */

int32_t ropesim_abi_version(void);

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ROPESIM_H */
