// Typed access to data/api-data.json (generated by scripts/generate-api-docs.py).

import fs from 'fs';
import path from 'path';

export interface ApiParam {
  name: string;
  type: string;
  description: string;
}

export interface ApiFunction {
  name: string;
  signature: string;
  params: ApiParam[];
  returns: string;
  docstring: string;
  example?: string;
}

export interface ApiClass {
  name: string;
  docstring: string;
  methods: ApiFunction[];
}

export interface ApiModule {
  name: string;
  docstring: string;
  classes: ApiClass[];
  functions: ApiFunction[];
}

export interface ApiData {
  generated: string;
  version: string;
  modules: ApiModule[];
}

export function loadApiData(): ApiData {
  const file = path.join(process.cwd(), 'data', 'api-data.json');
  if (!fs.existsSync(file)) {
    return { generated: '', version: 'dev', modules: [] };
  }
  return JSON.parse(fs.readFileSync(file, 'utf8')) as ApiData;
}
